---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: no-secrets
rules:
- apiGroups: ["*"]
  resources: ["deployments", "replicasets", "pods", "services", "ingresses", sqlclaims]
  verbs: ["get", "watch", "list"]
